name: Generate GitHub Snake Animation

on:
  schedule:
    # Runs every 12 hours to update the animation
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows you to manually run the action from the Actions tab
  push: # Optional: run on push to main/master
    branches:
      - main # Or 'master', depending on your default branch

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needs write permission to commit the generated graph back to the repo

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-snake.svg
          # Example for a dark-mode optimized snake:
          # svg_out_path: dist/github-snake-dark.svg?palette=github-dark

      - name: Commit and Push SVG
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/github-snake.svg # Make sure this path matches svg_out_path
          if git diff --staged --quiet; then
            echo "No changes to the snake animation."
          else
            git commit -m "chore: generate snake animation 🐍"
            git push
          fi
